"""Production-boundary primitives for a disposable Lambda GPU controller.

Nothing in this package contacts Lambda or GitHub at import time.  The live
transport is reachable only through :class:`LambdaLiveAdapter`, which requires
an API key read from an anonymous file descriptor and two independent runtime
authorization gates.
"""

from .adapter import (
    AccessIdentityReceipt,
    AmbiguousMutation,
    CloudInitWaitReceipt,
    ContractError,
    DiscoveryReceipt,
    EvidenceDirectoryReceipt,
    FirewallRule,
    HostIdentity,
    HostPreflightReceipt,
    ImmutablePlan,
    KnownHostsFileReceipt,
    LambdaHttpClient,
    LambdaLiveAdapter,
    LiveGates,
    MutationIntent,
    MutationIntentCallback,
    ProviderRequest,
    ProviderResponse,
    RuntimeBundle,
    RuntimeFrameReceipt,
    SecretBuffer,
    SnapshotReceipt,
    StrictSshBinding,
    build_immutable_plan,
    build_plan_from_discovery,
    build_strict_ssh_binding,
    capture_access_identity,
    capture_action_time_discovery,
    create_evidence_directory,
    dry_run_contract,
    generate_ephemeral_host_identity,
    load_runtime_bundle,
    read_jit_config_from_fd,
    reopen_evidence_directory,
    runtime_bundle_from_captured_files,
    validate_cloud_init_wait_receipt,
    validate_host_preflight_receipt,
    write_public_evidence,
    write_public_known_hosts,
    write_runtime_frame_and_close,
)

__all__ = [
    "AccessIdentityReceipt",
    "AmbiguousMutation",
    "CloudInitWaitReceipt",
    "ContractError",
    "DiscoveryReceipt",
    "EvidenceDirectoryReceipt",
    "FirewallRule",
    "HostIdentity",
    "HostPreflightReceipt",
    "ImmutablePlan",
    "KnownHostsFileReceipt",
    "LambdaHttpClient",
    "LambdaLiveAdapter",
    "LiveGates",
    "MutationIntent",
    "MutationIntentCallback",
    "ProviderRequest",
    "ProviderResponse",
    "RuntimeBundle",
    "SecretBuffer",
    "SnapshotReceipt",
    "StrictSshBinding",
    "RuntimeFrameReceipt",
    "build_immutable_plan",
    "build_plan_from_discovery",
    "build_strict_ssh_binding",
    "capture_access_identity",
    "dry_run_contract",
    "generate_ephemeral_host_identity",
    "load_runtime_bundle",
    "validate_cloud_init_wait_receipt",
    "validate_host_preflight_receipt",
    "capture_action_time_discovery",
    "create_evidence_directory",
    "read_jit_config_from_fd",
    "reopen_evidence_directory",
    "runtime_bundle_from_captured_files",
    "write_runtime_frame_and_close",
    "write_public_evidence",
    "write_public_known_hosts",
]
